### ISSUE TITLE
The number of crackmes differs between homepage and latest crackmes page

### ISSUE THREAD

**Issue by rivit98** [0xstan/crackmes.one#4]
Hi, 
I notices some discrepancy between the number of available crackmes (latest crackmes) and the number showed on the home page. Here is the explanation:

Number of crackmes on the home page: 3409
Number of crackmes calculated on the basis of the list of "latest crackmes":
* 50 * 67 = 3350  from https://crackmes.one/lasts/1 to https://crackmes.one/lasts/67
* and additional 29 crackmes here: https://crackmes.one/lasts/68
* https://crackmes.one/lasts/69 has 0 tasks

so total number here is: 3379 which is different from what is stated on the homepage (3409).

Should be easy to fix, probably home page is counting hidden tasks also
@sar5430

**Comment by moex3** [comment]
Yes, on the index page it's counting the hidden ones as well. This is just selecting every crackme, and counting it up.
https://github.com/sar5430/crackmes.one/blob/f5165fc74e7e655d1e35eab4848f664b02fa8c65/app/model/crackme.go#L32-L45

This one is selecting those that are visible.
https://github.com/sar5430/crackmes.one/blob/f5165fc74e7e655d1e35eab4848f664b02fa8c65/app/model/crackme.go#L120-L135

I think something like `c.Find(bson.M{"visible": true}).Count()` could work, if that's the intended behaviour of course.

Should be an easy fix.

**Comment by rivit98** [comment]
Could you make a PR? :D

I'm wondering if there are more places where hidden crackmes are also counted...

**Comment by moex3** [comment]
> I'm wondering if there are more places where hidden crackmes are also counted...

Yes, when it counts the crackme number for a user. It was used to detect if a submitted crackme got rejected or is it still pending or something. I don't think that is needed anymore. Also, same thing happens with solutions. But now I'm starting to think that this is intentional?

> Could you make a PR? :D

Maybe I will, but I don't want to test it right now (those python scripts really aren't the best), so I might just submit one without testing.
But if you want to, go ahead and submit one. Just make sure it builds.

**Comment by sar5430** [comment]
Do you think that modifying the `CountCrackmes` function to make it count only the visible ones is a proper solution to this issue ?

**Comment by moex3** [comment]
Yes, I think so. Either that, or adding another function or an argument that only counts the visible ones, if something else uses this to count the hidden ones as well. But as far as I know, only the index page uses that, and it's a good thing to only shows the visible ones.

**Comment by sar5430** [comment]
I pushed a commit that should fix the bug

**Comment by rivit98** [comment]
Great, I'm closing the issue ;)
