### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by SpamixOfficial** [0xstan/crackmes.one#9]
# How come the website is down?

Yea yea, I know this is not a "project  issue!, but I'm just wondering why the website is down. Is it maintenance or something else?

Thanks for any answers :D

**Comment by snowkluster** [comment]
had the same question

**Comment by SpamixOfficial** [comment]
@snowkluster got a response, seems to be the VPS that has made their prices higher. Sar wont have time until sunday to fix everything, so until then we will have to let our brains rest from crackmes.

btw im closing this issue now since i've gotten an answer
